USE DATABASE NETFLIX_TITLES;
USE WAREHOUSE NETFLIX;

-- create a view for missing data
CREATE OR REPLACE VIEW MISSING_DATA_VIEW AS
SELECT *
FROM NETFLIX_TITLES.PUBLIC.TITLES
WHERE TYPE IS NULL OR 
    TITLE IS NULL OR
    DIRECTOR IS NULL OR
    'CAST' IS NULL OR
    COUNTRY IS NULL OR
    RELEASE_YEAR IS NULL OR
    RATING IS NULL OR
    DURATION IS NULL OR
    LISTED_IN IS NULL OR
    DESCRIPTION IS NULL OR
    DATE_ADDED IS NULL;

-- check and count missing data
SELECT
  COUNT(CASE WHEN TYPE IS NULL THEN 1 END) AS MISSING_COUNT_TYPE,
  COUNT(CASE WHEN TITLE IS NULL THEN 1 END) AS MISSING_COUNT_TITLE,
  COUNT(CASE WHEN DIRECTOR IS NULL THEN 1 END) AS MISSING_COUNT_DIRECTOR,
  COUNT(CASE WHEN 'CAST' IS NULL THEN 1 END) AS MISSING_COUNT_CAST,
  COUNT(CASE WHEN COUNTRY IS NULL THEN 1 END) AS MISSING_COUNT_COUNTRY,
  COUNT(CASE WHEN RELEASE_YEAR IS NULL THEN 1 END) AS MISSING_COUNT_RELEASE_YEAR,
  COUNT(CASE WHEN RATING IS NULL THEN 1 END) AS MISSING_COUNT_RATING,
  COUNT(CASE WHEN DURATION IS NULL THEN 1 END) AS MISSING_COUNT_DURATION,
  COUNT(CASE WHEN LISTED_IN IS NULL THEN 1 END) AS MISSING_COUNT_LISTED_IN,
  COUNT(CASE WHEN DESCRIPTION IS NULL THEN 1 END) AS MISSING_COUNT_DESCRIPTION,
  COUNT(CASE WHEN DATE_ADDED IS NULL THEN 1 END) AS MISSING_COUNT_DATE_ADDED
FROM TITLES;