USE DATABASE NETFLIX_TITLES;
USE WAREHOUSE NETFLIX;
-- check if any title is added before it's been released
CREATE OR REPLACE VIEW CHECK_VALID_DATE_VIEW AS
SELECT *
FROM NETFLIX_TITLES.PUBLIC.TITLES T
WHERE TO_DATE(T.RELEASE_YEAR::VARCHAR, 'YYYY') > DATE_ADDED;

SELECT COUNT(*) FROM CHECK_VALID_DATE_VIEW