CREATE OR REPLACE TABLE NETFLIX_TITLES.PUBLIC.TITLES CLUSTER BY (RELEASE_YEAR)(
	SHOW_ID VARCHAR NOT NULL,
	TYPE VARCHAR,
	TITLE VARCHAR,
	DIRECTOR VARCHAR,
	CAST VARCHAR,
	COUNTRY VARCHAR,
	DATE_ADDED VARCHAR,
	RELEASE_YEAR NUMBER(38,0),
	RATING VARCHAR,
	DURATION VARCHAR,
	LISTED_IN VARCHAR,
	DESCRIPTION VARCHAR,
	primary key (SHOW_ID)
);
