USE DATABASE NETFLIX_TITLES;
USE WAREHOUSE NETFLIX;
SELECT T.TITLE,
    DATEDIFF(day, TO_DATE(T.RELEASE_YEAR::VARCHAR, 'YYYY'), T.DATE_ADDED) as Timespan
FROM NETFLIX_TITLES.PUBLIC.TITLES T
WHERE type = 'Movie'
ORDER BY Timespan DESC
LIMIT 1;